// Shim for lucide-react — the package's published types are missing some
// platform metadata in this install, so we declare it as a permissive
// module to keep the build green. Each export is treated as a React
// component that accepts any props.
declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react';
  export type LucideIcon = ComponentType<SVGProps<SVGSVGElement> & {
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
    absoluteStrokeWidth?: boolean;
  }>;
  const Icon: LucideIcon;
  export default Icon;
  export const Activity: LucideIcon;
  export const Anything: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const Award: LucideIcon;
  export const BadgeCheck: LucideIcon;
  export const Beaker: LucideIcon;
  export const Bell: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Calendar: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const Camera: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const CircleDollarSign: LucideIcon;
  export const Clock: LucideIcon;
  export const Cloud: LucideIcon;
  export const Download: LucideIcon;
  export const Droplets: LucideIcon;
  export const Dumbbell: LucideIcon;
  export const Filter: LucideIcon;
  export const Flame: LucideIcon;
  export const FlaskConical: LucideIcon;
  export const GitCompare: LucideIcon;
  export const GitFork: LucideIcon;
  export const Globe: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const Grid3x3: LucideIcon;
  export const Heart: LucideIcon;
  export const Layers: LucideIcon;
  export const Leaf: LucideIcon;
  export const List: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const Minus: LucideIcon;
  export const Moon: LucideIcon;
  export const Package: LucideIcon;
  export const Pause: LucideIcon;
  export const PauseCircle: LucideIcon;
  export const Phone: LucideIcon;
  export const Pill: LucideIcon;
  export const Play: LucideIcon;
  export const Plus: LucideIcon;
  export const Quote: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Settings2: LucideIcon;
  export const Shield: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const ShoppingBag: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const SkipForward: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Star: LucideIcon;
  export const Sun: LucideIcon;
  export const Sunrise: LucideIcon;
  export const Sunset: LucideIcon;
  export const Tag: LucideIcon;
  export const Thermometer: LucideIcon;
  export const ThumbsDown: LucideIcon;
  export const ThumbsUp: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Truck: LucideIcon;
  export const Wind: LucideIcon;
  export const X: LucideIcon;
  export const Zap: LucideIcon;
}
